### ISSUE TITLE
Remove 'no precompilation' requirement

### ISSUE THREAD

**Issue by japhb** [jnthn/oo-monitors#7]
Currently Monitors.pm6 contains a 'no precompilation' directive.  Since that directive is infectious (it affects all modules that _transitively_ depend on OO::Monitors) and OO::Monitors tends to be used deep in the core of applications, this can seriously slow startup time.

The directive remains because of an apparent serialization bug:

> 23:03	japhb	.tell jnthn Sadly, OO::Monitors still fails without 'no precompilation'.  When I comment it out and run `perl6 -I lib t/precomp.t` I immediately get: Missing serialize REPR function for REPR SCRef (SCRef)

**Comment by jonathanstowe** [comment]
If it's still there (and I haven't tested in a while,) the serialization fault really needs to be fixed in moar - I know where it happens but I don't know how it got there in the first place.

**Comment by jnthn** [comment]
I fixed the inability to serialize an `SCRef` in MoarVM just now. Unfortunately, that just gets us to another error. Looking further into that one.

**Comment by jnthn** [comment]
Note that the `callsame()` in the above golf is important and the bug goes away without it. This points to the Perl 6 optimizer, which refuses to perform certain optimizations if it sees `callsame`. Turns out that getting rid of `callsame` and pre-compiling with `--optimize=off` will also show up the bug. Summary: an optimization is hiding a precomp bug.

**Comment by jnthn** [comment]
Turn off the `delete_unused_autoslurpy` optimization and this fails without the `callsame()`. This is utterly weird by this point.

**Comment by jnthn** [comment]
So, it turns out that `%_` when passed to `compose` contains a special key `compiler_services`, which is an object used in order to more efficiently generate accessor methods. However, `%_` is unused, so the lexical is optimized away - until you have a `callsame`, at which point it shall not be optimized away because that poisons various optimizations. It's the presence of this `compiler_services` hash entry that messes up serialization.

**Comment by jnthn** [comment]
With Rakudo and MoarVM HEAD, together with a patch to this module to work around a remaining issue that will need some more involved fixes (3e9975f8c1436381cf774d01d24a049cc41de7e9), this module now works with `use precompilation` (3f63293ff5b3323afddeca0bd19bee9c3ed0da72). I've removed the `todo` from the test also. Will keep the RT on this topic open to track the remaining Rakudo fix in order that the workaround can be removed.
